apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: test-network-policy
  namespace: app-team1
spec:
  podSelector: {}
  policyTypes:
    - Ingress
#  ingress:
#    - from:
#        - podSelector: {}
#      ports:
#        - protocol: TCP
#          port: 80
